option(ADDR_SAN "Enable address sanitizer for memory related issues" OFF)
if (ADDR_SAN)
    add_compile_options(-fsanitize=address)
    add_link_options(-fsanitize=address)
endif ()

option(UB_SAN "Enable undefined behavior sanitizer" OFF)
if (UB_SAN)
    add_compile_options(-fsanitize=undefined)
    add_link_options(-fsanitize=undefined)
endif ()

option(THREAD_SAN "Enable thread behavior sanitizer" OFF)
if (THREAD_SAN)
    add_compile_options(-fsanitize=thread)
    add_link_options(-fsanitize=thread)
endif ()

option(LEAK_SAN "Enable thread behavior sanitizer" OFF)
if (LEAK_SAN)
    add_compile_options(-fsanitize=leak)
    add_link_options(-fsanitize=leak)
endif ()

option(MEMORY_SAN "Enable thread behavior sanitizer" OFF)
if (MEMORY_SAN)
    add_compile_options(-fsanitize=memory)
    add_link_options(-fsanitize=memory)
endif ()
